package entidades;
// Generated 19/07/2019 08:31:04 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Atencion generated by hbm2java
 */
public class Atencion  implements java.io.Serializable {


     private int idAtencion;
     private Mascotaporcliente mascotaporcliente;
     private String fechaAtencion;
     private String diagnostico;
     private Date horaAtencion;
     private int idPersonal;
     private int idTipoAtencion;

    public Atencion() {
    }

    public Atencion(int idAtencion, Mascotaporcliente mascotaporcliente, String fechaAtencion, String diagnostico, Date horaAtencion, int idPersonal, int idTipoAtencion) {
       this.idAtencion = idAtencion;
       this.mascotaporcliente = mascotaporcliente;
       this.fechaAtencion = fechaAtencion;
       this.diagnostico = diagnostico;
       this.horaAtencion = horaAtencion;
       this.idPersonal = idPersonal;
       this.idTipoAtencion = idTipoAtencion;
    }
   
    public int getIdAtencion() {
        return this.idAtencion;
    }
    
    public void setIdAtencion(int idAtencion) {
        this.idAtencion = idAtencion;
    }
    public Mascotaporcliente getMascotaporcliente() {
        return this.mascotaporcliente;
    }
    
    public void setMascotaporcliente(Mascotaporcliente mascotaporcliente) {
        this.mascotaporcliente = mascotaporcliente;
    }
    public String getFechaAtencion() {
        return this.fechaAtencion;
    }
    
    public void setFechaAtencion(String fechaAtencion) {
        this.fechaAtencion = fechaAtencion;
    }
    public String getDiagnostico() {
        return this.diagnostico;
    }
    
    public void setDiagnostico(String diagnostico) {
        this.diagnostico = diagnostico;
    }
    public Date getHoraAtencion() {
        return this.horaAtencion;
    }
    
    public void setHoraAtencion(Date horaAtencion) {
        this.horaAtencion = horaAtencion;
    }
    public int getIdPersonal() {
        return this.idPersonal;
    }
    
    public void setIdPersonal(int idPersonal) {
        this.idPersonal = idPersonal;
    }
    public int getIdTipoAtencion() {
        return this.idTipoAtencion;
    }
    
    public void setIdTipoAtencion(int idTipoAtencion) {
        this.idTipoAtencion = idTipoAtencion;
    }




}


